version: "3.3"

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - pgsql
    depends_on:
      - pgsql
    container_name: openapi_core_php_fpm

  pgsql:
    build:
      context: .
      dockerfile: deployment/local/docker/pgsql/Dockerfile
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./persistent_data/pgsql:/var/lib/postgresql/data
