version: "3.3"

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - pgsql
      - pgsql_testing
    depends_on:
      - pgsql
      - pgsql_testing
    container_name: openapi_core_php_fpm

  pgsql:
    image: postgres:11.3
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./persistent_data/pgsql:/var/lib/postgresql/data

  pgsql_testing:
    image: postgres:11.3
    ports:
      - "${DOCKER_PGSQL_TESTING_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_TESTING_DATABASE}
      POSTGRES_USER: ${DB_TESTING_USERNAME}
      POSTGRES_PASSWORD: ${DB_TESTING_PASSWORD}
